
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - .:/var/task
    environment:
      - APP_ENV=local
      # Other environment variables your Laravel app might need
